name: Tests

on:
  pull_request:
    branches:
      - develop
  push:
    branches:
      - develop

jobs:
  main:
    name: Unit Tests

    runs-on: ubuntu-latest

    if: "!contains(github.event.head_commit.message, '[ci skip]')"

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Test Suite
        run: tests/run
        env:
          TERM: xterm-256color
